//Can add more themes from here
export const ALL_THEMES = [
  {
    themeName: "Light",
    colors: {
      "--color-background": "#ffffff",
      "--color-primary": "#00d1b2",
      "--color-primary-light": "#00d1b238",
      "--color-primary-dark": "#049b84",
      "--color-secondary": "#7bccca",
      "--color-tertiary": "#ff94c4",
      "--color-text-primary": "black",
      "--color-text-secondary": "#363636",
      "--color-nav-hover": "#ccccccd5",
      "--color-gradient": "#303437",
      "--color-dark-gray": "#c5c4c2",
      "--transparent": "#ffffffbf",
    },
  },
  {
    themeName: "Dark",
    colors: {
      "--color-background": "black",
      "--color-primary": "#eb5757",
      "--color-primary-light": "#f28e8e31",
      "--color-primary-dark": "#eb3c3c",
      "--color-secondary": "#f9bf52",
      "--color-tertiary": "#1ab7ea",
      "--color-text-primary": "#ffffffe5",
      "--color-text-secondary": "#9a989a",
      "--color-nav-hover": "#1a1f28",
      "--color-gradient": "#303437",
      "--color-dark-gray": "#2c323f",
      "--transparent": "#111111bf",
    },
  },
  {
    themeName: "Purple",
    colors: {
      "--color-background": "#1e3253",
      "--color-primary": "#d884ff",
      "--color-primary-light": "#e4aaff3f",
      "--color-primary-dark": "#c243fd",
      "--color-secondary": "#eb505a",
      "--color-tertiary": "#aac86e",
      "--color-text-primary": "#ffffff",
      "--color-text-secondary": "#a0acbc",
      "--color-nav-hover": "#2c4c78",
      "--color-gradient": "#303437",
      "--color-dark-gray": "#2c4c78",
      "--transparent": "#21315bc5",
    },
  },
  {
    themeName: "Green",
    colors: {
      "--color-background": "#ecf5e3",
      "--color-primary": "#2d9641",
      "--color-primary-light": "#59976446",
      "--color-primary-dark": "#129029",
      "--color-secondary": "#b8723f",
      "--color-tertiary": "#b33938",
      "--color-text-primary": "#303e22",
      "--color-text-secondary": "#809070",
      "--color-nav-hover": "#c7e2ab",
      "--color-gradient": "#303437",
      "--color-dark-gray": "#c7e2ab",
      "--transparent": "#f0f0d57e",
    },
  },
  {
    themeName: "Gray",
    colors: {
      "--color-background": "#313437",
      "--color-primary": "#eb5757",
      "--color-primary-light": "#553b3d",
      "--color-primary-dark": "#f28e8e",
      "--color-secondary": "#f9bf52",
      "--color-tertiary": "#069ccd",
      "--color-text-primary": "#ebebeb",
      "--color-text-secondary": "#a0a2a3",
      "--color-nav-hover": "#474c50",
      "--color-gradient": "#303437",
      "--color-dark-gray": "#474c50",
      "--transparent": "#303437bf",
    },
  },
  {
    themeName: "Maroon",
    colors: {
      "--color-background": "#621832",
      "--color-primary": "#ffd845",
      "--color-primary-light": "#fce3891e",
      "--color-primary-dark": "#fbd344",
      "--color-secondary": "#d44159",
      "--color-tertiary": "#ceaaef",
      "--color-text-primary": "#fff",
      "--color-text-secondary": "#b7a0ab",
      "--color-nav-hover": "#79495c",
      "--color-gradient": "#303437",
      "--color-dark-gray": "#79495c",
      "--transparent": "#621832bf",
    },
  },
];

export const SKILLS = [
  {
    no: 0,
    id: "reactjs",
    name: "Reactjs",
    shortDescription: "Advanced",
    date: "June 2022",
    icon: "/assets/img/languageIcons/reactjs.png",
    logoAlt: "Shows reactjs logo",
    logoBackground: "skills",
  },
  {
    no: 1,
    id: "react-native",
    name: "React Native",
    shortDescription: "Advanced",
    date: "September 2022",
    icon: "/assets/img/languageIcons/reactjs.png",
    logoAlt: "Shows reactnative logo",
    logoBackground: "skills",
  },
  {
    no: 2,
    id: "vue-js",
    name: "Vue",
    shortDescription: "Advanced",
    date: "January 2023",
    icon: "/assets/img/languageIcons/vue.png",
    logoAlt: "Shows vue logo",
    logoBackground: "skills",
  },
  {
    no: 3,
    id: "vuetify",
    name: "Vuetify",
    shortDescription: "Advanced",
    date: "January 2023",
    icon: "/assets/img/languageIcons/vuetify.png",
    logoAlt: "Shows vuetify logo",
    logoBackground: "skills",
  },
  {
    no: 4,
    id: "sass",
    name: "SASS",
    shortDescription: "Advanced",
    date: "April 2022",
    icon: "/assets/img/languageIcons/sass.png",
    logoAlt: "Shows sass logo",
    logoBackground: "skills",
  },
  {
    no: 5,
    id: "html5",
    name: "HTML 5",
    shortDescription: "Advanced",
    date: "July 2021",
    icon: "/assets/img/languageIcons/html-5.png",
    logoAlt: "Shows html 5 logo",
    logoBackground: "skills",
  },
  {
    no: 6,
    id: "css3",
    name: "CSS 3",
    shortDescription: "Advanced",
    date: "July 2021",
    icon: "/assets/img/languageIcons/css-3.png",
    logoAlt: "Shows css 3 logo",
    logoBackground: "skills",
  },
  {
    no: 7,
    id: "javascript",
    name: "JavaScript",
    shortDescription: "Advanced",
    date: "December 2021",
    icon: "/assets/img/languageIcons/java-script.png",
    logoAlt: "Shows javascript logo",
    logoBackground: "skills",
  },
  {
    no: 8,
    id: "nodejs",
    name: "Nodejs",
    shortDescription: "Advanced",
    date: "August 2022",
    icon: "/assets/img/languageIcons/nodejs.png",
    logoAlt: "Shows nodejs logo",
    logoBackground: "skills",
  },
  {
    no: 9,
    id: "mongodb",
    name: "MongoDB",
    shortDescription: "Intermediate",
    date: "August 2022",
    icon: "/assets/img/languageIcons/mongoDB.png",
    logoAlt: "Shows mongodb logo",
    logoBackground: "skills",
  },
  {
    no: 10,
    id: "apollo",
    name: "Apollo GraphQL",
    shortDescription: "Intermediate",
    date: "December 2022",
    icon: "/assets/img/languageIcons/graphql.png",
    logoAlt: "Shows graphql logo",
    logoBackground: "skills",
  },
  {
    no: 11,
    id: "docker",
    name: "Docker",
    shortDescription: "Intermediate",
    date: "January 2023",
    icon: "/assets/img/languageIcons/docker.png",
    logoAlt: "Shows docker logo",
    logoBackground: "skills",
  },
  {
    no: 12,
    id: "mui",
    name: "Material UI",
    shortDescription: "Advanced",
    date: "September 2022",
    icon: "/assets/img/languageIcons/mui.png",
    logoAlt: "Shows material UI logo",
    logoBackground: "skills",
  },
  {
    no: 13,
    id: "git",
    name: "Git",
    shortDescription: "Advanced",
    date: "September 2022",
    icon: "/assets/img/languageIcons/github.png",
    logoAlt: "Shows nodejs logo",
    logoBackground: "skills",
  },
  {
    no: 14,
    id: "typescript",
    name: "TypeScript",
    shortDescription: "Advanced",
    date: "June 2022",
    icon: "/assets/img/languageIcons/typescript.png",
    logoAlt: "Shows typescript logo",
    logoBackground: "skills",
  },
];

export const EXPERIENCE = [
  {
    no: 0,
    id: "quantum",
    name: "React / React Native Intern",
    shortDescription: "Quantum Dynamics Corp",
    date: "September 2022 - December 2022",
    icon: "/assets/img/companyIcons/quantumDynamicsCorp.jpg",
    logoAlt: "Shows reactjs logo",
    logoBackground: "skills",
  },
];

export const EDUCATION_DETAILS = [
  {
    no: 0,
    id: "pda",
    name: "Poojya Doddappa Appa College Of Engineering",
    shortDescription: "Bachelor's degree, Computer Science",
    date: "2019 - 2023",
  },
  {
    no: 1,
    id: "gurukul",
    name: "Gurukul Independent P.U College",
    shortDescription: "Science",
    date: "2017 - 2019",
  },
  {
    no: 2,
    id: "vasavadatta",
    name: "Vasavadatta Vidya Vihar",
    shortDescription: "SSLC",
    date: "2005 - 2017",
  },
];

export const GAMES = [
  {
    no: 0,
    id: "csgo",
    name: "Counter Strike : Global Offensive",
    shortDescription:
      "Always loved this game. Lot of childhood memories connected to it.",
    date: "ID: 1086915975",
  },
  {
    no: 1,
    id: "valorant",
    name: "Valorant",
    shortDescription: "Basically counter strike but modern 😆.",
    date: "ID: Oopskiller#2415",
  },
];

export const BOOK_RECOMMENDATIONS = [
  {
    no: 0,
    id: "startwithwhy",
    name: "Start With WHY",
    shortDescription: "Simon Sinek",
    date: "Rank #1",
  },
  {
    no: 1,
    id: "thekiterunner",
    name: "The Kite Runner",
    shortDescription: "Khaled Hosseini",
    date: "Rank #2",
  },
  {
    no: 2,
    id: "uncletom",
    name: "Uncle Tom's Cabin",
    shortDescription: "Harriet Beecher Stowe",
    date: "Rank #3",
  },
  {
    no: 3,
    id: "tokillamockingbird",
    name: "To Kill a Mockingbird",
    shortDescription: "Harper Lee",
    date: "Rank #4",
  },
  {
    no: 4,
    id: "theboyinstripedpajamas",
    name: "The Boy in the Striped Pajamas",
    shortDescription: "John Boyne",
    date: "Rank #5",
  },
  {
    no: 5,
    id: "thehungergames",
    name: "The Hunger Games Series",
    shortDescription: "Suzanne Collins",
    date: "Rank #6",
  },
  {
    no: 6,
    id: "1984",
    name: "1984",
    shortDescription: "George Orwell",
    date: "Rank #7",
  },
];
