import { createSlice } from "@reduxjs/toolkit";

//Can add more projects from here
const OWN_PROJECTS = [
  {
    no: 0,
    id: "cryptinfo",
    name: "CryptInfo",
    shortDescription: "Live statistics of cryptocurrencies.",
    longDescription:
      "A web application that gives live statistics of more than 200 cryptocurrencies. Primary focus was to master MVC architecture and asynchronous functionalities with async-await.",
    date: "April 2022",
    live: "https://cryptinfo-musaib.netlify.app/",
    sourceCode: "https://github.com/mdmusaibali/CryptInfo",
    icon: "/assets/img/projectIcons/cryptinfo.png",
    images: [],
    logoBackground: "darkpink",
    logoAlt: "CryptInfo Logo",
  },
  {
    no: 1,
    id: "chefshat",
    name: "Chef's Hat",
    shortDescription: "A recipe handbook.",
    longDescription:
      "A web application made for home made chef's who LOVE cooking. Contains around 1 Lakh recipe's from all around the globe coming from forkify-v2 API. Aim was to learn and implement MVC architecture and asynchronous functionalities with async-await.",
    date: "April 2022",
    live: "https://chefshat.netlify.app/",
    sourceCode: "https://github.com/mdmusaibali/Chefs-Hat",
    icon: "/assets/img/projectIcons/chef-hat.png",
    images: [],
    logoBackground: "teal",
    logoAlt: "Chef's Hat Logo",
  },
  {
    no: 2,
    id: "maptodo",
    name: "Maptodo",
    shortDescription: "A map with a task on location.",
    longDescription:
      "Add a task at particular location, complete it and delete. As simple as that. With MapTodo you don't need to memorise your tasks, just leave it to Maptodo. No need to install any space consuming android app. It's all on your browser.",
    date: "December 2021",
    live: "https://mdmusaibali.github.io/MapTodo/",
    sourceCode: "https://github.com/mdmusaibali/MapTodo",
    icon: "/assets/img/projectIcons/map1.png",
    images: [],
    logoBackground: "lightgreen",
    logoAlt: "Maptodo Logo",
  },
  {
    no: 3,
    id: "hoodie",
    name: "Hoddie",
    shortDescription: "UI for a hoodie selling website.",
    longDescription:
      "Commercial website to sell Hoodies. Not fully commercial though 😂. Tried to implement add to cart feature using object programming. Primary focus was to learn some new JavsScript functionalities.",
    date: "December 2021",
    live: "https://mdmusaibali.github.io/Hoodie/",
    sourceCode: "https://github.com/mdmusaibali/Hoodie",
    icon: "/assets/img/projectIcons/hoodie1.png",
    images: [],
    logoBackground: "yellowishgolden",
    logoAlt: "Hoodie Logo",
  },
  {
    no: 4,
    id: "travella",
    name: "Travella",
    shortDescription: "UI for a vacation booking website.",
    longDescription:
      "My very first responsive modern website. Took me 2 days to complete, worth it. Gives a calm feeling to the user. You are free to use this commercially. Credit to the author is appreciated 😉.",
    date: "September 2021",
    live: "https://mdmusaibali.github.io/Travella/",
    sourceCode: "https://github.com/mdmusaibali/Travella",
    icon: "/assets/img/projectIcons/travella1.png",
    images: [],
    logoBackground: "lightpink",
    logoAlt: "Travella Logo",
  },
];
const PRACTICE_PROJECTS = [
  {
    no: 0,
    id: "expensetracker",
    name: "Expense tracker",
    shortDescription: "UI for a vacation booking website.",
    longDescription:
      "My second React.js project. Add any of your daily expenses and then analyse them at the end of each month.",
    date: "March 2022",
    live: "https://expensetracker-by-musaib.netlify.app/",
    sourceCode: "https://github.com/mdmusaibali/Expense-Tracker",
    icon: "/assets/img/projectIcons/expenseTracker.png",
    images: [],
    logoBackground: "teal",
    logoAlt: "Expense Tracker Logo",
  },
  {
    no: 1,
    id: "natours",
    name: "Natours",
    shortDescription: "Landing page for tours company.",
    longDescription:
      "Made this while i was leraning SASS from a course on udemy. This webpage looks modern and appealing. Primary focus was on scalability. Made this project scalable so that it is easy to maintain and easy to add any increments to the project.",
    date: "March 2022",
    live: "https://mdmusaibali.github.io/Natours/",
    sourceCode: "https://github.com/mdmusaibali/Natours",
    icon: "/assets/img/projectIcons/planet-earth.png",
    images: [],
    logoBackground: "lightgreen",
    logoAlt: "Natours Logo",
  },
  {
    no: 2,
    id: "bankist",
    name: "Bankist",
    shortDescription: "Landing page for banking system.",
    longDescription:
      "Design was made by Jonas. I made it responsive by making few changes to HTML and CSS file. Tried to implement script on my own and added bunch of scripts for responsive functionalities as well. To be honest, looks dashing 👌.",
    date: "January 2022",
    live: "https://mdmusaibali.github.io/Bankist",
    sourceCode: "https://github.com/mdmusaibali/Bankist",
    icon: "/assets/img/projectIcons/bank.png",
    images: [],
    logoBackground: "yellowishgolden",
    logoAlt: "Bankist Logo",
  },
  {
    no: 3,
    id: "omnifood",
    name: "Omnifood",
    shortDescription: "Landing page for food company.",
    longDescription:
      "After learning HTML and CSS, i tried to clone a website called Omnifood as a test to check my skills. It turned out Superb.",
    date: "August 2021",
    live: "https://mdmusaibali.github.io/Omnifood-clone/",
    sourceCode: "https://github.com/mdmusaibali/Omnifood-clone",
    icon: "/assets/img/projectIcons/salad.png",
    images: [],
    logoBackground: "lightpink",
    logoAlt: "Omnifood Logo",
  },
  {
    no: 4,
    id: "nexter",
    name: "Nexter",
    shortDescription: "UI for real estate site.",
    longDescription:
      "A clean minimalist user interface for a real estate selling site. Primary focus was to check out integration of grid with SASS.",
    date: "March 2022",
    live: "https://mdmusaibali.github.io/Nexter/",
    sourceCode: "https://github.com/mdmusaibali/Nexter",
    icon: "/assets/img/projectIcons/house.png",
    images: [],
    logoBackground: "teal",
    logoAlt: "Nexter Logo",
  },
  {
    no: 5,
    id: "trillo",
    name: "Trillo",
    shortDescription: "UI for hotel booking site.",
    longDescription:
      "A clean minimalist user interface for a hotel booking site. Primary focus was to check out integration of flexbox with SASS.",
    date: "March 2022",
    live: "https://mdmusaibali.github.io/Trillo/",
    sourceCode: "https://github.com/mdmusaibali/Trillo",
    icon: "/assets/img/projectIcons/hotel.png",
    images: [],
    logoBackground: "darkpink",
    logoAlt: "Trillo Logo",
  },
  {
    no: 6,
    id: "smalljavascriptprojects",
    name: "Small JavaScript projects",
    shortDescription: "Few of my javascript mini apps.",
    longDescription:
      "I'll be making few web pages using JavaScript in order to apply what i learnt. Main webpage is ugly rightnow, i will make it awesome soon. Hope you like it. There's few games inside. Enjoy 😁",
    date: "November 2021",
    live: "https://mdmusaibali.github.io/Small-JavaScript-Web-Projects/",
    sourceCode: "https://github.com/mdmusaibali/Small-JavaScript-Web-Projects",
    icon: "/assets/img/projectIcons/rubik.png",
    images: [],
    logoBackground: "teal",
    logoAlt: "Small JavaScript Logo",
  },
];

const projectsSlice = createSlice({
  name: "projects",
  initialState: {
    ownProjects: OWN_PROJECTS,
    practiceProjects: PRACTICE_PROJECTS,
  },
  reducers: {},
});

export default projectsSlice;
export const projectsAction = projectsSlice.actions;
